spring:
  application:
    name: servicio-hoteles-luis
server:
  port: 8010
  servlet:
    context-path: /hoteles
eureka:
  client:
    service-url:
      defaultZone: http://10.2.4.21:8761/eureka
  instance:
    ip-address: 10.2.4.21
    prefer-ip-address: true
    instance-id: 10.2.4.21:8010      
